INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Pan Africa Market', '1521 1st Ave, Seattle, WA', '47.608941', '-122.340145', 'restaurant', 'http://www.russianriver.com/site/cms/images/me_applewood-restaurant.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Buddha Thai & Bar', '2222 2nd Ave, Seattle, WA', '47.613591', '-122.344394', 'bar', 'http://www.romanaresort.com.vn/content/content_1958_2_thumb.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('The Melting Pot', '14 Mercer St, Seattle, WA', '47.624562', '-122.356442', 'restaurant', 'http://www.russianriver.com/site/cms/images/me_applewood-restaurant.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Ipanema Grill', '1225 1st Ave, Seattle, WA', '47.606366', '-122.337656', 'restaurant', 'http://www.russianriver.com/site/cms/images/me_applewood-restaurant.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Sake House', '2230 1st Ave, Seattle, WA', '47.612825', '-122.34567', 'bar', 'http://www.romanaresort.com.vn/content/content_1958_2_thumb.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Crab Pot', '1301 Alaskan Way, Seattle, WA', '47.605961', '-122.34036', 'restaurant', 'http://www.russianriver.com/site/cms/images/me_applewood-restaurant.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Mama\'s Mexican Kitchen', '2234 2nd Ave, Seattle, WA', '47.613975', '-122.345467', 'bar', 'http://www.romanaresort.com.vn/content/content_1958_2_thumb.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Wingdome', '1416 E Olive Way, Seattle, WA', '47.617215', '-122.326584', 'bar', 'http://www.romanaresort.com.vn/content/content_1958_2_thumb.jpg');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`, `imageLink`) VALUES ('Piroshky Piroshky', '1908 Pike pl, Seattle, WA', '47.610127', '-122.342838', 'restaurant', 'http://www.russianriver.com/site/cms/images/me_applewood-restaurant.jpg');
